### ISSUE TITLE
about submit json file

### ISSUE THREAD

**Issue by chenghuige** [AIChallenger/AI_Challenger#15]
in caption_validation_annotations_20170910.json 
 "image_id": "3cd32bef87ed98572bac868418521852ac3f6a70.jpg"
So the in the predicted json file for submit just be like below?
[
  {
    "caption": "一个面对着蓝天大海的女人坐在海边的沙滩椅子",
    "image_id": "3cd32bef87ed98572bac868418521852ac3f6a70"
  }
]
remove '.jpg' for each image ?

**Comment by zhhezhhe** [comment]
@chenghuige Yes.

**Comment by AIChallenger** [comment]
@chenghuige You are right.

**Comment by chenghuige** [comment]
Thanks, closed.
