### ISSUE TITLE
ai_challenger_keypoint_validation_20170911 关键点验证集中有json标注文件吗？

### ISSUE THREAD

**Issue by lxltaibo** [AIChallenger/AI_Challenger#21]
下载的ai_challenger_keypoint_validation_20170911 关键点验证集中没有json标注文件？是我下错了还是本来就没提供？

**Comment by AIChallenger** [comment]
@lxltaibo 你好，可能是下载错误，请验证下载文件的sha1sum值，
16cd0b5ac4d38e664806c80028f8d6670f918f15

**Comment by biyuehuang** [comment]
你好！ai_challenger_keypoint在哪里下载的？在官方网站找不到。谢谢

**Comment by lxltaibo** [comment]
是下载文件出了问题，多谢！
