### ISSUE TITLE
is this a known error?

### ISSUE THREAD

**Issue by fword** [AIChallenger/AI_Challenger#26]
NotFoundError: /home/sk/ai_challenger_caption_train_20170902/caption_train_images_20170902/e55ba6db106e61f50802ed3547b325ced2e32a3a.jpg

**Comment by AIChallenger** [comment]
@fword No, we did locate that image file in the directory. This is the sha1sum of caption training files: ecafb50a4bd29213772941a5a559d4f741c214b6 Probably you should check if the training file download was completed. Good luck!

**Comment by JinmingZhao** [comment]
This image is also not in my downloaded files and there are only 209961 images in the train set. I modify the script to filter these images in the json file, but not in my downloaded files.

**Comment by linoandy** [comment]
@JinmingZhao maybe your download wasn't completed. I have exactly 210000 images. You should calculate the Sha1 of the zip file you downloaded, and see if it matches with the one provided by the organizers, ecafb50a4bd29213772941a5a559d4f741c214b6

**Comment by JinmingZhao** [comment]
@linoandy yeah, the  Sha1 of my downloaded file is not equal to the provided.  And I think that ignore these images is a solution to solve this problem if the network is not very stable. Thanks.
