### ISSUE TITLE
中文caption,inference特别慢

### ISSUE THREAD

**Issue by JinmingZhao** [AIChallenger/AI_Challenger#28]
validation和test都是一张一张的caption, 1080卡，测一次要几个小时，大家也没遇到这个问题吗？

**Comment by chenghuige** [comment]
每次inference 一组 batch size可以取500

**Comment by JinmingZhao** [comment]
@chenghuige  提供的 run_inference.py 是不支持这个的，每次beam_search的时候传的是一张图片，用batch_size需要自己根据train的inputs格式去改？

**Comment by chenghuige** [comment]
@JinmingZhao 别的框架不太清楚 如果你试用tf的话 可以搜一下beam search相关的，im2txt提供的是out graph的beam search 每次inference 只能有一个图片
你可以参考google/seq2seq提供的ingraph beam search

**Comment by JinmingZhao** [comment]
@chenghuige 非常感谢! 刚开始做caption, 见谅！

**Comment by daicoolb** [comment]
你好，请问中文caption inference特别慢的问题解决了么
