### ISSUE TITLE
caption eval hang run_evaluations_test.py

### ISSUE THREAD

**Issue by chenghuige** [AIChallenger/AI_Challenger#3]
hang on computing meteor

Error: Could not find or load main class edu.stanford.nlp.process.PTBTokenizer
Error: Could not find or load main class edu.stanford.nlp.process.PTBTokenizer
setting up scorers...
computing Bleu score...
{'reflen': 0, 'guess': [0, 0, 0, 0], 'testlen': 0, 'correct': [0, 0, 0, 0]}
ratio: 1e-06
Bleu_1: 0.000
Bleu_2: 0.000
Bleu_3: 0.000
Bleu_4: 0.000
computing METEOR score...

**Comment by AIChallenger** [comment]
- 首先建议检查下环境是否配好，例如：java 1.8.0。
- 如果环境没问题，建议查看
/AI_Challenger/AI_Challenger_eval_public/caption_eval/coco_caption/pycxevalcap/tokenizer/ptbtokenizer.py
- 如果依然有问题，建议查看[Stanford Tokenizer](http://nlp.stanford.edu/software/tokenizer.shtml) ，[Stanford CoreNLP 3.4.1](http://nlp.stanford.edu/software/corenlp.shtml).
希望对你的问题有帮助。

**Comment by chenghuige** [comment]
@AIChallenger  ok I put stanford tokenizer at the path of tokenizer and now can run ok before computing meteor score, still hang on computing meteor..

loading annotations into memory...
0:00:00.000165
creating index...
index created!
Loading and preparing results...     
.loading annotations into memory...
0:00:00.000136
creating index...
index created!
Loading and preparing results...     
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.234 seconds.
Prefix dict has been built succesfully.
DONE (t=0.23s)
creating index...
index created!
.loading annotations into memory...
0:00:00.000183
creating index...
index created!
Loading and preparing results...     
.loading annotations into memory...
0:00:00.000153
creating index...
index created!
Loading and preparing results...     
.loading annotations into memory...
0:00:00.000202
creating index...
index created!
Loading and preparing results...     
DONE (t=0.00s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 217 tokens at 3932.58 tokens per second.
PTBTokenizer tokenized 44 tokens at 302.52 tokens per second.
setting up scorers...
computing Bleu score...
{'reflen': 43, 'guess': [42, 39, 36, 33], 'testlen': 42, 'correct': [34, 24, 16, 12]}
ratio: 0.976744186024
Bleu_1: 0.790
Bleu_2: 0.689
Bleu_3: 0.591
Bleu_4: 0.520
computing METEOR score...

**Comment by chenghuige** [comment]
@AIChallenger  Thanks, fixed, due to missing tar. close.
