### ISSUE TITLE
caption_eval 运行测试demo报错

### ISSUE THREAD

**Issue by WuLC** [AIChallenger/AI_Challenger#4]
在目录 `AI_Challenger/AI_Challenger_eval_public/caption_eval` 下运行

 `python run_evaluations.py -submit  ./data/id_to_test_caption.json -ref ./data/id_to_words.json`

报错如下
loading annotations into memory...
0:00:00
creating index...
index created!
Loading and preparing results...
Building prefix dict from the default dictionary ...
Loading model from cache c:\users\lc\appdata\local\temp\jieba.cache
Loading model cost 0.420 seconds.
Prefix dict has been built succesfully.
{'error': 1}

OS：windows 10
python版本：2.7.13

**Comment by AIChallenger** [comment]
考虑到windows环境下可能出现的问题，代码做了部分修改      
将图片名到int的映射从 `int(int(hashlib.sha256(img_name).hexdigest(), 16) % sys.maxint)` 替换为 `self.image2hash[img_name]`，改用字典，key是图像名，value是对应的int值。    
   
如果还有错，建议修改ptbtokenizer.py的53行 `p_tokenizer = subprocess.Popen(cmd, cwd=path_to_jar_dirname, stdout=subprocess.PIPE)` 为windows相应的用法。         
其中cmd = ['java', '-cp', 'stanford-corenlp-3.4.1.jar', 'edu.stanford.nlp.process.PTBTokenizer', '-preserveLines', '-lowerCase', 'tmpeq6wbU']

**Comment by WuLC** [comment]
好，谢谢

**Comment by AIChallenger** [comment]
@自己做reference.json，很灵活，只要保证你自己的图片名有自己相应的int型id就好，保证一一对应就好。

**Comment by WuLC** [comment]
明白了，谢谢

**Comment by AIChallenger** [comment]
@WuLC Windows环境跑通了是吧？

**Comment by WuLC** [comment]
是的

**Comment by WuLC** [comment]
是的，之前我跑自己的 `reference.json` 时，采用的映射关系也是用这种方式 `int(int(hashlib.sha256(img_name).hexdigest(), 16) % sys.maxint)`，不过能够评分，没有报错。

是不是之前的demo 中 hash 后恰好有冲突？

**Comment by AIChallenger** [comment]
@WuLC 应该是不同系统hashlib的计算结果不一样。

**Comment by WuLC** [comment]
好，还是要抽空看下源码 >_<，关掉issue了

**Comment by JinmingZhao** [comment]
@WuLC  python run_evaluations_test.py 脚本会报错吗？ coco_res = coco.loadRes(json_predictions_file) 这里报错了， 由于id_to_test_words 没有images等关键字， 遇到过这个问题吗？
