### ISSUE TITLE
给的验证集数据的标注，左右是乱的？

### ISSUE THREAD

**Issue by luohuan2uestc** [AIChallenger/AI_Challenger#5]

**Comment by AIChallenger** [comment]
@luohuan2uestc 问的是image caption的问题吗？ 因为每个人看图片的角度不一样，有的以图片里某个人的方位描述，有的就是以图片的左右描述。我们并没有对左右有规定，完全以标注人员为主，5个描述可能会出现你提到的情况。

**Comment by luohuan2uestc** [comment]
那你有没有考虑过，我们预测的结果如何跟你标注的进行判断呢？难道我们要猜标注人的参考左还是右吗？

**Comment by luohuan2uestc** [comment]
那你们要对数据集重新标注了。否则怎么验证？难道算法去自己猜吗？

**Comment by luohuan2uestc** [comment]
我问的人的姿态估计的

**Comment by AIChallenger** [comment]
@luohuan2uestc 你问的是keypoint吧？人身上关键点的编号顺序可以参考我们的官网上面的说明。

**Comment by luohuan2uestc** [comment]
是的，但是我发现你们给的验证集的数据的顺序和你们官网给的不一样，官网上是以图片上的人为中心标注的，可是验证集上却感觉是随意左右标注的，麻烦你们检查一下，谢谢，我给你们写过邮件，也没有回。举例：0002605c53fb92109a3f2de4fc3ce06425c3b61f.jpg
其他还有很多。
