### ISSUE TITLE
cacography

### ISSUE THREAD

**Issue by deepblacksky** [AIChallenger/AI_Challenger#7]
https://github.com/AIChallenger/AI_Challenger/blob/a41de91a6544fea6cd3a68879a6f3150b14d8fd9/AI_Challenger_eval_public/scene_classification_eval/scene_eval.py#L66
warnning -> warning
https://github.com/AIChallenger/AI_Challenger/blob/a41de91a6544fea6cd3a68879a6f3150b14d8fd9/AI_Challenger_eval_public/scene_classification_eval/scene_eval.py#L114
Evalation -> Evaluation
原谅我是一个强迫症患者:)

**Comment by AIChallenger** [comment]
@deepblacksky Thanks !
